### ISSUE TITLE
how compare from string eg. file_get_contents()

### ISSUE THREAD

**Issue by erlangparasu** [akosnikhazy/compare-images#1]

**Comment by akosnikhazy** [comment]
Nice idea :D I should have thought about this 6 years ago. I will not update it to do this, but feel free to do so if you want.

So this class only supports image files.

On the other hand this is not really an issue, as the class made to compere image sources based on their pixel's mean values. For base64 encoded image (text) your best track to make an image source from it in a temp folder [like in this solution](https://stackoverflow.com/questions/15153776/convert-base64-string-to-an-image-file), then feed it to the compare() method for comparison.

**Comment by erlangparasu** [comment]
Thanks :D
